name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -s -X POST \
            "http://95.216.191.135:8000/api/v1/deploy?uuid=cx6lh3f6cdxzpyw2de4vxbzm&force=true" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
